// =============================================================================
// app/api/cron/newsletter-generate/route.ts
// Vercel Cron handler — runs daily at 06:00 UTC (see vercel.json).
//
// 1. Calls Claude to generate newsletter content for 'atleta' and 'coach'
// 2. Builds the email HTML for each audience
// 3. Inserts draft rows (status='pending') into newsletter_drafts
// 4. Logs the 'generated' action in newsletter_logs
// 5. Sends a push notification to all staff to review the pending drafts
//
// Timezone note: cron fires at 06:00 UTC.
// Adjust the vercel.json schedule if your org is not UTC-based.
// =============================================================================

import { NextRequest, NextResponse } from 'next/server';
import { requireCronAuth }               from '@/lib/cron/auth';
import { supabaseAdmin }                 from '@/lib/supabase-admin';
import { generateNewsletterContent, buildEmailHTML } from '@/lib/newsletter/generator';
import { notifyAdminsNewsletterReady }   from '@/lib/newsletter/onesignal';
import type { NewsletterAudiencia }      from '@/lib/newsletter/types';

export const runtime = 'nodejs';
// Give Claude enough time to generate both newsletters
export const maxDuration = 120;

// Scheduled for tomorrow at 13:00 UTC (= 7:00 AM Mexico/Obregón UTC-6).
// The generate cron fires at 12:00 UTC (= 6 AM local) — admins have ~25h to approve.
function tomorrowAt7amLocalUTC(): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() + 1);
  d.setUTCHours(13, 0, 0, 0); // 7am UTC-6
  return d.toISOString();
}

const AUDIENCES: NewsletterAudiencia[] = ['atleta', 'coach'];

export async function GET(req: NextRequest): Promise<NextResponse> {
  const denied = requireCronAuth(req);
  if (denied) return denied;

  const appUrl      = process.env.NEXT_PUBLIC_APP_URL ?? 'https://aodeporte.com';
  const scheduledFor = tomorrowAt7amLocalUTC();
  const results: Array<{
    audiencia: NewsletterAudiencia;
    status:    'generated' | 'error';
    draftId?:  string;
    error?:    string;
  }> = [];

  for (const audiencia of AUDIENCES) {
    try {
      // 1. Generate content via Claude
      const content  = await generateNewsletterContent(audiencia);
      const htmlContent = buildEmailHTML(content, audiencia, appUrl);

      // 2. Insert draft
      const { data: draft, error: insertErr } = await supabaseAdmin
        .from('newsletter_drafts')
        .insert({
          audiencia,
          asunto:        content.asunto,
          preview_text:  content.preview,
          intro:         content.intro,
          tips_json:     content.tips,
          html_content:  htmlContent,
          status:        'pending',
          scheduled_for: scheduledFor,
        })
        .select('id')
        .single();

      if (insertErr || !draft) {
        throw new Error(insertErr?.message ?? 'Failed to insert draft');
      }

      // 3. Audit log
      await supabaseAdmin.from('newsletter_logs').insert({
        draft_id:   draft.id,
        action:     'generated',
        actor_id:   null,
        actor_role: 'system',
        note:       `Generated by cron for ${audiencia} audience`,
        metadata:   { scheduled_for: scheduledFor },
      });

      results.push({ audiencia, status: 'generated', draftId: draft.id });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      results.push({ audiencia, status: 'error', error: message });
    }
  }

  // 4. Push notification to all staff (best-effort)
  const generated = results.filter((r) => r.status === 'generated').length;
  if (generated > 0) {
    await notifyAdminsNewsletterReady(generated).catch(() => {});
  }

  const hasError = results.some((r) => r.status === 'error');
  return NextResponse.json(
    { ok: !hasError, results },
    { status: hasError ? 207 : 200 }
  );
}
